// HistoryPage.idl
import "HistoryPageViewModel.idl";

namespace Folderify
{
    runtimeclass HistoryPage : Microsoft.UI.Xaml.Controls.Page
    {
        HistoryPage();
        HistoryPageViewModel MainViewModel{ get; };
    }
}
