// PlaylistInfo.idl
namespace Folderify
{
    runtimeclass PlaylistInfo : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
		PlaylistInfo(String playlistPath, String numberOfSongs);
        String PlaylistPath;
        String PlaylistTitle;
        String NumberOfSongs;
    }
}