// PlaylistSelectionPage.idl
import "PlaylistSelectionPageViewModel.idl";

namespace Folderify
{
    runtimeclass PlaylistSelectionPage : Microsoft.UI.Xaml.Controls.Page
    {
        PlaylistSelectionPage();
	    PlaylistSelectionPageViewModel MainViewModel{ get; };
    }
}
