// QueuePage.idl
import "QueuePageViewModel.idl";

namespace Folderify
{
    runtimeclass QueuePage : Microsoft.UI.Xaml.Controls.Page
    {
        QueuePage();
        QueuePageViewModel MainViewModel{ get; };
    }
}
