// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Folderify
{
    [default_interface]
    runtimeclass SongsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SongsPage();
        Int32 MyProperty;
    }
}
