// SongInfo.idl
namespace Folderify
{
    runtimeclass SongInfo : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
		SongInfo(String songTitle, String playlistTitle);
        String SongTitle;
		String PlaylistTitle;
    }
}