// SongInfo.idl
namespace Folderify
{
    runtimeclass SongInfo : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
		SongInfo(String songPath);
        String SongTitle;
		String PlaylistTitle;
        String SongPath;
    }
}